1
-- SELECT * FROM CLIENTE
-- WHERE MUNICIPIO LIKE (SELECT MUNICIPIO FROM CLIENTE WHERE NOME LIKE 'Manoel')
-- AND NOME NOT LIKE 'Manoel'

2
-- SELECT DATA_PEDIDO, VALOR FROM PEDIDO
-- WHERE VALOR < (SELECT AVG(VALOR) FROM PEDIDO)

--3
-- SELECT DISTINCT P.IDPEDIDO, P.DATA_PEDIDO, P.VALOR, C.NOME, V.NOME_VEND
-- FROM PEDIDO P, CLIENTE C, VENDEDOR V, ITEM_PEDIDO IP
-- WHERE P.IDCLIENTE = C.IDCLIENTE
-- AND P.IDVENDEDOR = V.IDVENDEDOR
-- AND P.IDPEDIDO = IP.IDPEDIDO
-- AND IP.IDPEDIDO IN (SELECT IDPEDIDO
-- 					FROM ITEM_PEDIDO
-- 					GROUP BY IDPEDIDO
-- 					HAVING COUNT(*) >= 2)



4
-- SELECT NOME FROM CLIENTE
-- WHERE MUNICIPIO IN (SELECT MUNICIPIO FROM TRANSPORTADORA
-- 						 WHERE NOME_TRANSP LIKE 'BS. Transportes')

5
-- SELECT NOME, MUNICIPIO FROM CLIENTE
-- WHERE MUNICIPIO IN (SELECT MUNICIPIO FROM TRANSPORTADORA 
-- 						WHERE IDTRANSPORTADORA IN(1,2))
-- ORDER BY MUNICIPIO
