-- CREATE TABLE TUTOR(
-- 	COD_TUTOR SERIAL PRIMARY KEY,
-- 	NOME_TUTOR VARCHAR(100) NOT NULL
-- );
-- CREATE TABLE TELEFONE(
-- 	COD_TEL SERIAL PRIMARY KEY,
-- 	NUM_TEL VARCHAR(11),
-- 	COD_TUTOR INT NOT NULL REFERENCES TUTOR(COD_TUTOR)
-- );
-- CREATE TYPE LOGS AS ENUM('RUA', 'AVENIDA', 'SERVIDAO', 'MARGINAL', 'TRAVESSA');
-- CREATE TABLE ENDERECO(
-- 	COD_END SERIAL PRIMARY KEY,
-- 	COD_TUTOR INT NOT NULL REFERENCES TUTOR(COD_TUTOR),
-- 	TIPO_LOG LOGS NOT NULL DEFAULT'RUA',
-- 	NOME_LOG VARCHAR(100) NOT NULL,
-- 	NUMERO VARCHAR(20) NOT NULL,
-- 	BAIRRO VARCHAR(100)NOT NULL,
-- 	CIDADE VARCHAR(100) NOT NULL,
-- 	UF VARCHAR(2) NOT NULL DEFAULT 'SC',
-- 	CEP VARCHAR(8)NOT NULL
-- );

-- CREATE TABLE ESPECIALIDADE(
-- 	COD_ESPECIALIDADE SERIAL PRIMARY KEY,
-- 	NOME_ESPECIALIDADE VARCHAR(50) NOT NULL UNIQUE
-- );
-- CREATE SEQUENCE SEQ_VET INCREMENT 10 START 1000;
-- CREATE TABLE VETERINARIO(
-- 	COD_VET INT PRIMARY KEY DEFAULT NEXTVAL('SEQ_VET'),
-- 	NOME VARCHAR(100) NOT NULL,
-- 	REG_PROF VARCHAR(50),
-- 	COD_ESPECIALIDADE INT REFERENCES ESPECIALIDADE(COD_ESPECIALIDADE)
-- );

-- CREATE TABLE ESPECIE(
-- 	COD_ESP SERIAL PRIMARY KEY,
-- 	NOME_ESP VARCHAR(50) NOT NULL UNIQUE
-- );
-- CREATE TABLE RACA(
-- 	COD_RACA SERIAL PRIMARY KEY,
-- 	NOME_RACA VARCHAR(100) NOT NULL,
-- 	COD_ESP INT NOT NULL REFERENCES ESPECIE(COD_ESP)
-- );
-- CREATE TABLE ANIMAL(
-- 	COD_ANIMAL SERIAL PRIMARY KEY,
-- 	COD_RACA INT NOT NULL REFERENCES RACA(COD_RACA),
-- 	DT_NASC DATE,
-- 	PESO FLOAT NOT NULL,
-- 	COD_TUTOR INT NOT NULL REFERENCES TUTOR(COD_TUTOR)
-- );

-- ALTER TABLE ANIMAL ADD COLUMN NOME VARCHAR(100) NOT NULL;
-- SELECT * FROM ANIMAL;

-- CREATE TABLE CONSULTA(
-- 	COD_CONSULTA SERIAL PRIMARY KEY,
-- 	DATA_CONSULTA DATE DEFAULT CURRENT_DATE,
-- 	DIAGNOSTICO VARCHAR(200) NOT NULL,
-- 	TRATAMENTO VARCHAR(200) NOT NULL,
-- 	COD_VET INT NOT NULL REFERENCES VETERINARIO(COD_VET),
-- 	COD_ANIMAL INT NOT NULL REFERENCES ANIMAL(COD_ANIMAL)
-- );

-- INSERT INTO TUTOR (NOME_TUTOR)
-- VALUES('PAULO DA SILVA'), ('MARIA APARECIDA MARTINS'), ('SIMONE SOUZA'), 
-- ('REGINALDO FARIAS'), ('MARLENE HOFFMAN'), ('AROLDO ARAUJO'), ('PEDRO PASCAL'), 
-- ('MIGUEL LIVRAMENTO'), ('ANA CLAUDIA SOARES'), ('GUSTAVO GUIMARARES'), 
-- ('ALFREDO FAPPI');
-- SELECT * FROM TUTOR

-- INSERT INTO TELEFONE(NUM_TEL, COD_TUTOR)
-- VALUES('48994796252', 1), ('48994796984', 2), ('48994793657', 3), ('48994798796', 4),
--  ('48994797264', 5), ('48997962351', 6), ('48994793215', 7), ('48994793512', 8), 
-- ('48994795136', 8), ('48994795476', 9), ('48994792689', 10),('48994796734', 11), 
-- ('48994791572', 11);
-- SELECT * FROM TELEFONE;


-- UPDATE TELEFONE SET NUM_TEL = 47994856452
-- WHERE COD_TUTOR = 2;

-- UPDATE TELEFONE SET NUM_TEL = 49994793512
-- WHERE COD_TEL = 9;

-- INSERT INTO ENDERECO (COD_TUTOR, TIPO_LOG, NOME_LOG, NUMERO, BAIRRO, CIDADE, UF, CEP)
-- VALUES
-- (1, 'RUA', 'DAS FLORES', '123', 'JARDIM DAS ACACIAS', 'FLORIANOPOLIS', 'SC', '88010000'),
-- (2, 'AVENIDA', 'BEIRA MAR', '456', 'CENTRO', 'JOINVILLE', 'SC', '89200000'),
-- (3, 'TRAVESSA', 'SÃO JOÃO', '789', 'SANTO ANTÔNIO', 'BLUMENAU', 'SC', '89010000'),
-- (4, 'SERVIDAO', 'DOS PINHEIROS', '321', 'VILA NOVA', 'CRICIUMA', 'SC', '88810000'),
-- (5, 'MARGINAL', 'DO RIO', '654', 'SÃO MIGUEL', 'ITAJAI', 'SC', '88300000'),
-- (6, 'RUA', 'CENTENARIO', '987', 'CENTRO', 'CHAPECÓ', 'SC', '89800000'),
-- (7, 'AVENIDA', 'BRASIL', '159', 'JARDIM AMERICA', 'LAGES', 'SC', '88500000'),
-- (8, 'TRAVESSA', 'DOS LIRIOS', '753', 'BELA VISTA', 'TUBARÃO', 'SC', '88700000'),
-- (9, 'SERVIDAO', 'DA PAZ', '258', 'SAO JOSE', 'SAO JOSE', 'SC', '88100000'),
-- (10, 'MARGINAL', 'DA PRAIA', '357', 'CANTO', 'BALNEARIO CAMBORIU', 'SC', '88330000'),
-- (11, 'RUA', 'DOS VETERINARIOS', '951', 'VILA NOVA', 'PALHOÇA', 'SC', '88130000');

SELECT * FROM ENDERECO
WHERE CIDADE  NOT LIKE 'SAO JOSE'
ORDER BY BAIRRO