--CRIANDO USUARIOS/USER
CREATE USER FELIPE WITH PASSWORD '1234';
CREATE USER VINI WITH PASSWORD '1234';
CREATE USER SCHEILA WITH PASSWORD '1234';
CREATE USER PAULO WITH PASSWORD '1234';
CREATE USER MARIA WITH PASSWORD '1234';
CREATE USER PATRICIA WITH PASSWORD '1234';
CREATE USER LUIZ WITH PASSWORD '1234';
CREATE USER CLAUDIA WITH PASSWORD '1234';
CREATE USER ROBERTO WITH PASSWORD '1234';


--CRIANDO TABELAS
CREATE TABLE CLIENTE(
	COD_CLI SERIAL PRIMARY KEY,
	NOME_CLI VARCHAR(100) NOT NULL
);

CREATE TABLE FINANCEIRO(
	COD SERIAL PRIMARY KEY,
	PAGAMENTO FLOAT NOT NULL,
	COD_CLI INT NOT NULL REFERENCES CLIENTE(COD_CLI)
);

CREATE TABLE CARGO(
	COD_CARGO SERIAL PRIMARY KEY,
	DESCRICAO VARCHAR(50) NOT NULL
);

CREATE TABLE FUNCIONARIO(
	MATRICULA SERIAL PRIMARY KEY,
	NOME_FUNC VARCHAR(100) NOT NULL,
	COD_CARGO INT NOT NULL REFERENCES CARGO(COD_CARGO),
	SALARIO NUMERIC(10,2) NOT NULL
);

CREATE TABLE PRODUTO(
	COD_PROD SERIAL PRIMARY KEY,
	NOME_PROD VARCHAR(50) NOT NULL,
	PRECO NUMERIC(10,2) NOT NULL
);

CREATE TABLE VENDA(
	COD_VENDA SERIAL PRIMARY KEY,
	COD_PROD INT NOT NULL REFERENCES PRODUTO(COD_PROD),
	COD_CLI INT NOT NULL REFERENCES CLIENTE(COD_CLI),
	QTD INT NOT NULL,
	DATA_VENDA DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE CHAMADO(
	COD_CHAMADO SERIAL PRIMARY KEY,
	DESCRICAO VARCHAR NOT NULL,
	DATA_CHAMADO DATE NOT NULL DEFAULT CURRENT_DATE
);


--POPULANDO AS TABELAS
INSERT INTO CLIENTE (NOME_CLI) VALUES
('Ana Paula'),
('João Ribeiro'),
('Marcos Silva'),
('Fernanda Santos'),
('Carlos Almeida');

INSERT INTO FINANCEIRO (PAGAMENTO, COD_CLI) VALUES
(250.75, 1),
(130.00, 2),
(499.90, 3),
(89.50, 4),
(920.00, 5);

INSERT INTO CARGO (DESCRICAO) VALUES
('Analista de Sistemas'),
('Técnico de Suporte'),
('Gerente de TI'),
('Auxiliar Administrativo'),
('Desenvolvedor Backend');

INSERT INTO FUNCIONARIO (NOME_FUNC, COD_CARGO, SALARIO) VALUES
('Bruno Martins', 1, 4500.00),
('Camila Rocha', 2, 2800.00),
('Ricardo Teixeira', 3, 7500.00),
('Juliana Moreira', 4, 2300.00),
('Henrique Lopes', 5, 6200.00);

INSERT INTO PRODUTO (NOME_PROD, PRECO) VALUES
('Mouse sem fio', 89.90),
('Teclado mecânico', 350.00),
('Monitor 24 polegadas', 899.00),
('Headset gamer', 199.90),
('Webcam HD', 120.00);

INSERT INTO VENDA (COD_PROD, COD_CLI, QTD, DATA_VENDA) VALUES
(1, 1, 2, '2025-01-10'),
(2, 3, 1, '2025-01-11'),
(4, 2, 1, '2025-01-12'),
(5, 5, 3, '2025-01-12'),
(3, 4, 1, '2025-01-13');

INSERT INTO CHAMADO (DESCRICAO, DATA_CHAMADO) VALUES
('Erro no sistema de vendas', '2025-01-10'),
('Instabilidade no servidor', '2025-01-11'),
('Solicitação de criação de usuário', '2025-01-12'),
('Problema no acesso ao banco de dados', '2025-01-13'),
('Atualização de software necessária', '2025-01-14');


--CRIANDO GRUPOS/FUNÇÕES/ROLE
CREATE ROLE TI;
CREATE ROLE ADM;
CREATE ROLE RH;
CREATE ROLE VENDAS;


--DANDO AOS USUARIOS SEUS GRUPOS/FUNÇÕES/ROLE
GRANT TI TO FELIPE;
GRANT TI TO VINI;
GRANT ADM TO SCHEILA;
GRANT ADM TO PAULO;
GRANT ADM TO MARIA;
GRANT RH TO PATRICIA;
GRANT VENDAS TO LUIZ;
GRANT VENDAS TO CLAUDIA;
GRANT VENDAS TO ROBERTO;

--DEFININDO ACESSOS/PERMISSOES
GRANT ALL ON ALL TABLES IN SCHEMA PUBLIC TO TI;
GRANT ALL ON ALL SEQUENCES IN SCHEMA PUBLIC TO TI;

GRANT SELECT, INSERT, UPDATE ON FINANCEIRO, CLIENTE TO ADM;
GRANT ALL ON ALL SEQUENCES IN SCHEMA PUBLIC TO ADM;

GRANT ALL ON CARGO, FUNCIONARIO TO RH;
GRANT ALL ON ALL SEQUENCES IN SCHEMA PUBLIC TO RH;

GRANT SELECT ON CLIENTE TO VENDAS;
GRANT SELECT, UPDATE, INSERT ON VENDA TO VENDAS;
GRANT ALL ON ALL SEQUENCES IN SCHEMA PUBLIC TO VENDAS;


SELECT * FROM PRODUTO;
INSERT INTO PRODUTO (NOME_PROD, )