--CRIAÇÃO DAS TABELAS--

-- CREATE TABLE FORNECEDOR (
-- 	ID_FORNECEDOR SERIAL PRIMARY KEY,
-- 	NOME_FORNECEDOR VARCHAR(100) NOT NULL,
-- 	CIDADE VARCHAR(60) NOT NULL,
-- 	CONTATO VARCHAR(15) NOT NULL
-- );

-- CREATE TYPE CTG_ENUM AS ENUM ('INFORMATICA', 'TELEFONIA', 'ENTRETENIMENTO', 'ACESSORIOS');
-- CREATE TABLE PRODUTO(
-- 	ID_PRODUTO SERIAL PRIMARY KEY,
-- 	NOME_PRODUTO VARCHAR(100) NOT NULL,
-- 	CATEGORIA CTG_ENUM NOT NULL,
-- 	PRECO FLOAT NOT NULL,
-- 	QTD_ESTOQUE INT NOT NULL,
-- 	ID_FORNECEDOR INT NOT NULL REFERENCES FORNECEDOR(ID_FORNECEDOR)
-- )

-- CREATE TYPE STTS_ENUM AS ENUM ('PENDENTE', 'EM EXECUCAO', 'CONCLUIDA');
-- CREATE TABLE MANUTENCAO(
-- ID_MANUTENCAO SERIAL PRIMARY KEY,
-- DATA_SOLICITACAO DATE NOT NULL DEFAULT CURRENT_DATE,
-- STATUS STTS_ENUM NOT NULL,
-- ID_PRODUTO INT NOT NULL REFERENCES PRODUTO(ID_PRODUTO)
-- )



--INSERÇÃO DE DADOS--

-- INSERT INTO FORNECEDOR (NOME_FORNECEDOR, CIDADE, CONTATO) VALUES
-- ('TECH SUPPLY IMPORTADORA', 'SÃO PAULO', '1133224455'),
-- ('ELETRO CENTER DISTRIBUIDORA', 'CAMPINAS', '1938876655'),
-- ('DIGITAL WORLD TECNOLOGIA', 'SOROCABA', '1533012200');

-- INSERT INTO PRODUTO (NOME_PRODUTO, CATEGORIA, PRECO, QTD_ESTOQUE, ID_FORNECEDOR) VALUES
-- ('NOTEBOOK DELL INSPIRON 15', 'INFORMATICA', 3800.00, 10, 2),
-- ('SMARTPHONE SAMSUNG GALAXY A55', 'TELEFONIA', 2200.00, 15, 1),
-- ('SMART TV LG 55 POL', 'ENTRETENIMENTO', 3200.00, 5, 1),
-- ('TABLET LENOVO M10', 'INFORMATICA', 1250.00, 12, 3),
-- ('HEADSET LOGITECH G435', 'ACESSORIOS', 480.00, 20, 1);

-- INSERT INTO MANUTENCAO (DATA_SOLICITACAO, STATUS, ID_PRODUTO) VALUES
-- ('2025-09-10', 'PENDENTE', 1),
-- ('2025-09-12', 'EM EXECUCAO', 3),
-- ('2025-09-14', 'CONCLUIDA', 5),
-- ('2025-09-21', 'PENDENTE', 2),
-- ('2025-09-16', 'PENDENTE', 4),
-- ('2025-09-12', 'CONCLUIDA', 1);



--CONSULTAS--

-- 1) listar todos os produtos com estoque abaixo de 10 unidades 
-- SELECT * FROM PRODUTO
-- WHERE QTD_ESTOQUE < 10

-- 2) exibir os produtos e seus respectivos fornecedores
-- SELECT P.NOME_PRODUTO, F.NOME_FORNECEDOR
-- FROM PRODUTO P, FORNECEDOR F
-- WHERE P.ID_FORNECEDOR = F.ID_FORNECEDOR;

-- 3) mostrar a quantidade total de solicitações de manutenção do produto 1
-- SELECT P.NOME_PRODUTO, COUNT(M.ID_MANUTENCAO) AS TOTAL
-- FROM PRODUTO P, MANUTENCAO M
-- WHERE P.ID_PRODUTO = M.ID_PRODUTO
-- AND P.ID_PRODUTO = 1
-- GROUP BY(P.NOME_PRODUTO);

-- 4) exibir as manutenções com status "pendente" ordenadas por data
-- SELECT * FROM MANUTENCAO
-- WHERE STATUS = 'PENDENTE'
-- ORDER BY DATA_SOLICITACAO;

-- 5) calcular o valor total de produtos em estoque 
-- SELECT SUM(QTD_ESTOQUE) FROM PRODUTO;