--CRIA EXTENSÃO (O SE NÃO EXISTIR É OPCIONAL E SOBRESCREVE CASO JA EXISTA)
--essa extensão ignora o case sensitive nas buscas, ignorando maiusculo e minusculo
CREATE EXTENSION IF NOT EXISTS CITEXT;

CREATE TABLE ALUNO(
	ALU_ID SERIAL PRIMARY KEY,
	ALU_NOME CITEXT
);

INSERT INTO ALUNO(ALU_NOME) VALUES('MARIA'), ('maria'), ('Maria'), ('PEDRO');

SELECT * FROM ALUNO WHERE ALU_NOME = 'MAria'


--CRIA A EXTENSÃO DE CRIPTOGRAFIA
CREATE EXTENSION IF NOT EXISTS PGCRYPTO;

--MOSTRA COMO FICARIA A SENHA CRIPTOGRAFADA COM 'MD5'
SELECT ENCODE(DIGEST('12345', 'MD5'), 'HEX');


ALTER TABLE ALUNO ADD COLUMN SENHA TEXT;
TRUNCATE TABLE ALUNO
--INSERE UM REGISTRO COM SENHA E CRIPTOGRAFA ELA
INSERT INTO ALUNO(ALU_NOME, SENHA) VALUES ('MATHEUS', CRYPT('123', 'M@TH3U$'));
INSERT INTO ALUNO(ALU_NOME, SENHA) VALUES ('MATHEUS', CRYPT('123', GEN_SALT('MD5')));
SELECT * FROM ALUNO

--MOSTRA A SENHA CRIPTOGRAFADA
SELECT (SENHA = CRYPT('123', SENHA)) FROM ALUNO WHERE ALU_NOME = 'MATHEUS'


--FUNCAO PARA CRIPTOGRAFAR SENHA SEM MOSTRAR A SENHA REAL NO RETORNO DA QUERY
CREATE OR REPLACE FUNCTION CRIPTOGRAFA(SENHA_CRIPTO TEXT)
RETURNS TEXT AS $$
DECLARE DADO_CRIPTOGRAFADO TEXT;
BEGIN
	DADO_CRIPTOGRAFADO = CRYPT(SENHA_CRIPTO, GEN_SALT('MD5'));
	RETURN DADO_CRIPTOGRAFADO;
END;
$$ LANGUAGE PLPGSQL;

--INSERE REGISTRO JA CRIPTOGRAFANDO SENHA
INSERT INTO ALUNO (ALU_NOME, SENHA) VALUES('VICENTE', CRIPTOGRAFA('S&n@1'));
SELECT * FROM ALUNO;


--FUNCAO PARA DESCRIPTOGRAFAR SENHA
CREATE OR REPLACE FUNCTION VERIFICA_LOGIN(ID_USER INT)
RETURNS TEXT AS $$
DECLARE DADO_DECRIPTOGRAFADO TEXT;
BEGIN
	SELECT(SENHA = CRYPT('S&n@', SENHA)) FROM ALUNO
	WHERE ALU_ID = ID_USER INTO DADO_DECRIPTOGRAFADO;
	RETURN DADO_DECRIPTOGRAFADO;
END;
$$LANGUAGE PLPGSQL;

SELECT VERIFICA_LOGIN(11)

