CREATE OR REPLACE FUNCTION EXIBE_MSG()
RETURNS VARCHAR AS
$$
DECLARE MSG VARCHAR;
BEGIN
	MSG = 'SEJAM BEM VINDOS!';
	RETURN MSG;
END;
$$
LANGUAGE PLPGSQL;
SELECT EXIBE_MSG('OLÁ, ALUNOS');





CREATE OR REPLACE FUNCTION SOMA_NUMS(N1 INT, N2 INT)
RETURNS TEXT AS
$$
BEGIN
	RETURN 'A SOMA DOS NÚMEROS É: ' || N1 || ' E ' || N2 || ' É ' || N1 + N2;
END;
$$
LANGUAGE PLPGSQL;

--DROP FUNCTION soma_nums(integer, integer)
SELECT NOME_PRODUTO, SOMA_NUMS(45,25) AS SOMA, VALOR_UNITARIO FROM PRODUTO




CREATE OR REPLACE FUNCTION FORMATA_MOEDA(VAL FLOAT)
RETURNS VARCHAR AS 
$$
BEGIN
	RETURN 'R$' || ROUND(CAST(VAL AS NUMERIC), 2);
END;
$$
LANGUAGE PLPGSQL;

SELECT NOME_PRODUTO, FORMATA_MOEDA(VALOR_UNITARIO) AS PRECO FROM PRODUTO;





CREATE OR REPLACE FUNCTION CLASSIFICA_PROD(VAL DOUBLE PRECISION)
RETURNS TEXT AS 
$$
BEGIN
	IF VAL < 120 THEN
		RETURN 'BARATO';
	ELSIF VAL < 500 THEN
		RETURN 'INTERMEDIÁRIO';
	ELSE 
		RETURN 'CARO';
	END IF;
END;
$$ LANGUAGE PLPGSQL;
SELECT NOME_PRODUTO, FORMATA_MOEDA(VALOR_UNITARIO) AS PRECO, 
CLASSIFICA_PROD(VALOR_UNITARIO) FROM PRODUTO;





CREATE OR REPLACE FUNCTION INSERE_PROD(NOME VARCHAR(50), VALOR NUMERIC(10,2))
RETURNS VARCHAR AS $$
BEGIN
	INSERT INTO PRODUTO(NOME_PRODUTO, VALOR_UNITARIO)
	VALUES(NOME, VALOR);
	RETURN 	CONCAT('REGISTRO SALVO COM SUCESSO: ', NOME, ' - ', VALOR);
END;
$$ LANGUAGE PLPGSQL;

SELECT INSERE_PROD('TABLET', 960.50);
SELECT * FROM PRODUTO






CREATE VIEW TOTAL2 AS 
SELECT P.NOME_PRODUTO, P.VALOR_UNITARIO, IP.QUANTIDADE
FROM PRODUTO P, ITEM_PEDIDO IP
WHERE P.IDPRODUTO = IP.IDPRODUTO;

CREATE OR REPLACE FUNCTION CALC_TOTAL(VALOR FLOAT, QTD INT)
RETURNS TEXT AS $$
BEGIN
	RETURN SUM(VALOR * QTD);
END;
$$ LANGUAGE PLPGSQL;

SELECT NOME_PRODUTO, VALOR_UNITARIO, QUANTIDADE,
CALC_TOTAL(VALOR_UNITARIO, QUANTIDADE) AS TOTAL
FROM TOTAL2 ORDER BY QUANTIDADE DESC;