CREATE TABLE DEPARTAMENTO(
	COD_DEPARTAMENTO SERIAL PRIMARY KEY,
	NOME_DEPARTAMENTO VARCHAR(30) NOT NULL
);
CREATE TABLE SETOR(
	COD_SETOR SERIAL PRIMARY KEY,
	NOME_SETOR VARCHAR(30) NOT NULL,
	COD_DEPARTAMENTO INT NOT NULL,
	FOREIGN KEY (COD_DEPARTAMENTO) REFERENCES DEPARTAMENTO(COD_DEPARTAMENTO)
);
CREATE SEQUENCE SEQ_FUNC INCREMENT 1 START 1500;
CREATE TABLE FUNCIONARIO(
	MATRICULA INT PRIMARY KEY DEFAULT NEXTVAL('SEQ_FUNC') NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	COD_SETOR INT NOT NULL,
	SALARIO FLOAT NOT NULL,
	FOREIGN KEY (COD_SETOR) REFERENCES SETOR(COD_SETOR)
);

ALTER TABLE FUNCIONARIO ALTER COLUMN SALARIO SET DEFAULT 0.0;

CREATE TABLE ATUALIZACAO_SALARIAL(
	LOG_ALTERACAO SERIAL PRIMARY KEY,
	MATRICULA_FUNC INT NOT NULL,
	DATA_ALTERACAO TIMESTAMP NOT NULL,
	SAL_ANTERIOR FLOAT NOT NULL,
	SAL_ATUAL FLOAT NOT NULL,
	FOREIGN KEY (MATRICULA_FUNC) REFERENCES FUNCIONARIO(MATRICULA)
);

--DROP TABLE ATUALIZACAO_SALARIAL;

-- POPULANDO AS TABELAS
INSERT INTO DEPARTAMENTO (NOME_DEPARTAMENTO) VALUES ('OPERACIONAL');
INSERT INTO SETOR (NOME_SETOR, COD_DEPARTAMENTO) VALUES ('ENGENHARIA', 1);
INSERT INTO FUNCIONARIO (NOME, COD_SETOR, SALARIO) VALUES ('ANA', 1, 4200.00);

--CRIA FUNÇÃO PARA POPULAR A TABELA DE ATUALIZACAO_SALARIAL, A FUNÇÃO RETORNA UM TRIGGER
CREATE OR REPLACE FUNCTION ATUALIZA_SALARIO()
RETURNS TRIGGER AS $$
BEGIN
	IF(OLD.SALARIO IS NULL) THEN
		INSERT INTO ATUALIZACAO_SALARIAL(MATRICULA_FUNC, DATA_ALTERACAO, SAL_ANTERIOR, SAL_ATUAL)
		VALUES(NEW.MATRICULA, NOW(), 0.0, NEW.SALARIO);
	ELSE
		INSERT INTO ATUALIZACAO_SALARIAL(MATRICULA_FUNC, DATA_ALTERACAO, SAL_ANTERIOR, SAL_ATUAL)
		VALUES(NEW.MATRICULA, NOW(), OLD.SALARIO, NEW.SALARIO);
	END IF;
	RETURN NULL;
END;
$$ LANGUAGE PLPGSQL;

--TRIGGER CRIADO
CREATE TRIGGER TG_ATUALIZA_SALARIO
AFTER INSERT OR UPDATE 
ON FUNCIONARIO
FOR EACH ROW
EXECUTE PROCEDURE ATUALIZA_SALARIO();

--TESTE PARA VER O TRIGGER FUNCIONANDO
INSERT INTO FUNCIONARIO (NOME, COD_SETOR, SALARIO) VALUES ('LUIS', 1, 1500.00);
SELECT * FROM ATUALIZACAO_SALARIAL

SELECT * FROM FUNCIONARIO

--TESTE 2 PARA VER O TRIGGER FUNCIONANDO
UPDATE FUNCIONARIO 
SET SALARIO = 5000.50
WHERE MATRICULA = 1500;