-- 1
-- SELECT NOME_VEND FROM VENDEDOR
-- ORDER BY NOME_VEND

--2
-- SELECT * FROM PRODUTO
-- WHERE VALOR_UNITARIO > 200.00
-- ORDER BY VALOR_UNITARIO;

--3
-- SELECT NOME_PRODUTO, VALOR_UNITARIO, ROUND((VALOR_UNITARIO + 
-- (VALOR_UNITARIO/10)),2) AS PRECO_REAJUSTADO FROM PRODUTO
-- ORDER BY NOME_PRODUTO;

--4
-- SELECT MUNICIPIO, UF FROM CLIENTE
-- WHERE UF = 'RS';

--5
-- SELECT * FROM PEDIDO
-- WHERE DATA_PEDIDO BETWEEN '2008/04/10' AND '2008/04/25'
-- ORDER BY VALOR;

--6
-- SELECT * FROM PEDIDO
-- WHERE VALOR BETWEEN 1000.00 AND 1500.00

--7
-- SELECT * FROM PEDIDO
-- WHERE VALOR NOT BETWEEN 100.00 AND 500.00

--8
-- SELECT  V.NOME_VEND, P.*
-- FROM VENDEDOR V, PEDIDO P
-- WHERE V.IDVENDEDOR = P.IDVENDEDOR
-- AND V.NOME_VEND LIKE 'André'
-- ORDER BY VALOR DESC

--9
-- SELECT C.NOME, P.* 
-- FROM CLIENTE C, PEDIDO P
-- WHERE C.IDCLIENTE = P.IDCLIENTE
-- AND C.NOME LIKE 'Manoel'

--10
-- SELECT C.NOME, V.NOME_VEND, P.*
-- FROM CLIENTE C, VENDEDOR V, PEDIDO P
-- WHERE C.IDCLIENTE = P.IDCLIENTE
-- AND V.IDVENDEDOR = P.IDVENDEDOR
-- AND C.NOME LIKE 'Jéssica'
-- AND V.NOME_VEND LIKE 'André'

--11
-- SELECT T.NOME_TRANSP, P.* 
-- FROM TRANSPORTADORA T, PEDIDO P
-- WHERE T.NOME_TRANSP LIKE 'União Transportes'

--12
-- SELECT V.NOME_VEND, P.* 
-- FROM VENDEDOR V, PEDIDO P
-- WHERE V.NOME_VEND LIKE 'Maria'
-- OR V.NOME_VEND LIKE 'Aline'
-- ORDER BY V.NOME_VEND

--13
-- SELECT * FROM CLIENTE
-- WHERE MUNICIPIO LIKE 'União da Vitória'
-- OR MUNICIPIO LIKE 'Porto União'

--14
-- SELECT * FROM CLIENTE
-- WHERE MUNICIPIO NOT LIKE 'União da Vitória'
-- AND MUNICIPIO NOT LIKE 'Porto União'

--15
-- SELECT * FROM CLIENTE
-- WHERE LOGRADOURO IS NULL

--16
-- SELECT * FROM CLIENTE
-- WHERE LOGRADOURO LIKE 'Av.%';

--17
-- SELECT * FROM VENDEDOR
-- WHERE NOME_VEND LIKE 'S%'

--18
-- SELECT * FROM VENDEDOR
-- WHERE NOME_VEND LIKE '%a'

--19
-- SELECT * FROM VENDEDOR
-- WHERE NOME_VEND NOT LIKE 'A%'

--20
-- SELECT MUNICIPIO, UF FROM CLIENTE
-- WHERE MUNICIPIO LIKE 'P%'
-- AND UF LIKE 'SC'

--21 => NÃO TEM FORNECEDORES

--22
-- SELECT PED.IDPEDIDO, PROD.NOME_PRODUTO
-- FROM PEDIDO PED, ITEM_PEDIDO IP, PRODUTO PROD 
-- WHERE PED.IDPEDIDO = IP.IDPEDIDO
-- AND IP.IDPRODUTO = PROD.IDPRODUTO
-- AND PED.IDPEDIDO = 1

--23
-- SELECT PED.IDPEDIDO, PROD.NOME_PRODUTO
-- FROM PEDIDO PED, ITEM_PEDIDO IP, PRODUTO PROD
-- WHERE PED.IDPEDIDO = IP.IDPEDIDO
-- AND IP.IDPRODUTO = PROD.IDPRODUTO
-- AND PED.IDPEDIDO IN (6, 10)


