--QUESTÃO 1 - Registrar ações em log

CREATE OR REPLACE FUNCTION LOG_ALTERACAO_NOME()
RETURNS TRIGGER AS $$
BEGIN
	IF NEW.NOME <> OLD.NOME THEN
		INSERT INTO LOGEVENTOS(TABELA, DESCRICAO)
		VALUES ('ALUNO', 'NOME DO ALUNO ALTERADO DE ' || OLD.NOME || ' PARA ' || NEW.NOME);
	END IF;
	RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

CREATE TRIGGER TG_LOG_ALTERACAO_NOME
AFTER UPDATE
ON ALUNO
FOR EACH ROW
WHEN (OLD.NOME IS DISTINCT FROM NEW.NOME)
EXECUTE FUNCTION LOG_ALTERACAO_NOME;

UPDATE ALUNO 
SET NOME = 'Thiago Ribeiro'
WHERE ID_ALUNO = 4;

SELECT * FROM LOGEVENTOS




--QUESTÃO 2 - Bloquear matrículas duplicadas

CREATE OR REPLACE FUNCTION MATRICULA_DUPLICADA()
RETURNS TRIGGER AS $$
DECLARE EXISTE_MATRICULA BOOLEAN := FALSE;
BEGIN
	SELECT TRUE
	INTO EXISTE_MATRICULA
	FROM MATRICULA
	WHERE ID_ALUNO = NEW.ID_ALUNO
	AND ID_CURSO = NEW.ID_CURSO;

	IF EXISTE_MATRICULA THEN
		RAISE EXCEPTION 'Aluno já matriculado nesse curso';
	END IF;
	RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

CREATE TRIGGER TG_MATRICULA_DUPLICADA
BEFORE INSERT ON MATRICULA
FOR EACH ROW
EXECUTE FUNCTION MATRICULA_DUPLICADA();

INSERT INTO Matricula (id_aluno, id_curso) 
VALUES (1, 1)




--QUESTÃO 3 - Atualizar status do pagamento

CREATE OR REPLACE FUNCTION ATUALIZA_PAGAMENTO()
RETURNS TRIGGER AS $$
BEGIN
	IF NEW.VALOR > 0 THEN
		UPDATE PAGAMENTO
		SET STATUS = 'PAGO'
		WHERE ID_PAGAMENTO = NEW.ID_PAGAMENTO;
	END IF;
	RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

CREATE TRIGGER TG_ATUALIZA_PAGAMENTO
AFTER INSERT ON PAGAMENTO
FOR EACH ROW
EXECUTE FUNCTION ATUALIZA_PAGAMENTO();

SELECT * FROM PAGAMENTO



--QUESTÃO 4 - Desativar cursos automaticamente

CREATE OR REPLACE FUNCTION DESATIVA_CURSO()
RETURNS TRIGGER AS $$
BEGIN
	IF NEW.CARGA_HORARIA < 10 THEN
		NEW.ATIVO := FALSE;
	END IF;
	RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

CREATE TRIGGER TG_DESATIVA_CURSO
BEFORE INSERT OR UPDATE
ON CURSO
FOR EACH ROW
EXECUTE FUNCTION DESATIVA_CURSO();

SELECT * FROM CURSO



--QUESTÃO 5 - Registrar alterações financeiras
CREATE OR REPLACE FUNCTION LOG_ALTERACAO_PAGAMENTO()
RETURNS TRIGGER AS $$
BEGIN
	IF NEW.VALOR <> OLD.VALOR THEN
		INSERT INTO LOGEVENTOS(TABELA, DESCRICAO)
		VALUES ('PAGAMENTO', 'PAGAMENTO ' || NEW.ID_PAGAMENTO || ' ALTERADO DE ' || OLD.VALOR || ' PARA ' || NEW.VALOR);
	END IF;
	RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

CREATE TRIGGER TG_LOG_ALTERACAO_PAGAMENTO
AFTER UPDATE
ON PAGAMENTO
FOR EACH ROW
WHEN (OLD.VALOR IS DISTINCT FROM NEW.VALOR)
EXECUTE FUNCTION LOG_ALTERACAO_PAGAMENTO();

UPDATE PAGAMENTO
SET VALOR = 500
WHERE ID_PAGAMENTO = 1;

SELECT * FROM LOGEVENTOS