CREATE TYPE STTS_ENUM AS ENUM ('DISPONÍVEL', 'EM MANUTENÇÃO', 'FORA DE OPERAÇÃO');
CREATE TABLE VEICULO (
	COD_VEICULO SERIAL PRIMARY KEY,
	PLACA VARCHAR(7) NOT NULL UNIQUE,
	MODELO VARCHAR(100) NOT NULL,
	ANO_FAB INT NOT NULL,
	QUILOMETRAGEM FLOAT NOT NULL,
	STATUS STTS_ENUM NOT NULL DEFAULT 'DISPONÍVEL'
);
CREATE TABLE MOTORISTA (
	COD_MOTORISTA SERIAL PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	CNH VARCHAR(9) NOT NULL UNIQUE,
	CIDADE_ORIGEM VARCHAR(100) NOT NULL
);
CREATE TABLE TELEFONE (
	COD_TEL SERIAL PRIMARY KEY,
	NUM_TEL VARCHAR(11) NOT NULL,
	COD_MOTORISTA INT NOT NULL REFERENCES MOTORISTA(COD_MOTORISTA)
);
CREATE TABLE VIAGEM (
	COD_VIAGEM SERIAL PRIMARY KEY,
	DATA_SAIDA DATE NOT NULL,
	DESTINO VARCHAR(100) NOT NULL,
	KM_PERCORRIDO INT NOT NULL,
	COD_VEICULO INT NOT NULL REFERENCES VEICULO(COD_VEICULO),
	COD_MOTORISTA INT NOT NULL REFERENCES MOTORISTA(COD_MOTORISTA)
);
CREATE TYPE TIPO_ENUM AS ENUM ('ACIDENTE', 'MANUTENÇÃO', 'ATRASO');
CREATE TABLE OCORRENCIA (
	COD_OCORRENCIA SERIAL PRIMARY KEY,
	TIPO TIPO_ENUM NOT NULL,
	DESCRICAO VARCHAR(200) NOT NULL,
	COD_VIAGEM INT NOT NULL REFERENCES VIAGEM(COD_VIAGEM)
);